import { Bar, BarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { money } from "../api";
import { CaseTable } from "../components/CaseTable";
import type { CaseRow, Dashboard } from "../types";

const titleFor = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

export function MerchantPage({ dashboard, cases, onCase, onNewRecovery, onReviews }: { dashboard: Dashboard | null; cases: CaseRow[]; onCase: (id: string) => void; onNewRecovery: () => void; onReviews: () => void }) {
  const totalAtRisk = cases.filter((item) => item.status !== "RECOVERED").reduce((total, item) => total + item.amount, 0);
  const confirmed = dashboard?.money_recovered ?? 0;
  const active = dashboard?.active_recoveries ?? 0;
  const reviews = dashboard?.human_review_count ?? 0;
  const recoveryRate = dashboard?.recovery_rate ?? 0;
  const activity = cases.slice(0, 5);
  const hour = new Date().getHours();
  const greeting = hour < 12 ? "Good morning" : hour < 18 ? "Good afternoon" : "Good evening";

  return <div className="dashboard-page">
    <section className="welcome-row"><div><p className="eyebrow">OVERVIEW</p><h2>{greeting}</h2><p>Track collection activity, customer responses, and confirmed recovery outcomes.</p></div><div className="period-control"><span>Period</span><button>All activity <i>⌄</i></button></div></section>
    <section className="balance-card"><div className="balance-copy"><span>Confirmed recovery value</span><strong>{money(confirmed)}</strong><small>Only Razorpay-confirmed payments are included.</small></div><div className="balance-divider" /><div className="balance-stat"><span>Cases in progress</span><b>{active}</b><small>Across all recovery modules</small></div><div className="balance-stat"><span>Recovery rate</span><b>{recoveryRate}%</b><small>Completed recovery cases</small></div><button className="balance-action" onClick={onNewRecovery}>Create recovery <span>→</span></button></section>
    <section className="metric-grid"><article><div className="metric-head"><span>Open payment value</span><i className="metric-icon amber">₹</i></div><strong>{money(totalAtRisk)}</strong><small>Across {active} active recovery cases</small></article><article><div className="metric-head"><span>Confirmed recoveries</span><i className="metric-icon green">✓</i></div><strong>{money(confirmed)}</strong><small>Provider-confirmed revenue only</small></article><article><div className="metric-head"><span>Human review</span><i className="metric-icon violet">!</i></div><strong>{reviews}</strong><small>{reviews ? "Cases awaiting a decision" : "No actions awaiting review"}</small></article><article><div className="metric-head"><span>Total cases</span><i className="metric-icon blue">≡</i></div><strong>{dashboard?.total_cases ?? 0}</strong><small>Current workspace activity</small></article></section>
    <section className="quick-actions"><div className="section-heading"><div><p className="eyebrow">QUICK ACTIONS</p><h2>Run your next collection action</h2></div></div><div className="quick-action-grid"><button onClick={onNewRecovery}><span className="quick-icon">+</span><b>New recovery case</b><small>Assess a payment signal and contact path</small><i>→</i></button><button onClick={onReviews}><span className="quick-icon review-icon">✓</span><b>Review decisions</b><small>{reviews ? `${reviews} case${reviews === 1 ? "" : "s"} waiting for approval` : "No reviews waiting"}</small><i>→</i></button><button onClick={() => activity[0] && onCase(activity[0].case_id)} disabled={!activity.length}><span className="quick-icon record-icon">↗</span><b>Latest case record</b><small>{activity[0] ? `${activity[0].customer_name} · ${money(activity[0].amount)}` : "No activity yet"}</small><i>→</i></button></div></section>
    <section className="dashboard-main-grid"><section className="panel volume-panel"><div className="panel-title"><div><p className="eyebrow">PAYMENT INSIGHTS</p><h2>Recovery workload</h2></div><button className="text-control">By module <i>⌄</i></button></div><ResponsiveContainer width="100%" height={245}><BarChart data={dashboard?.domain_breakdown ?? []} margin={{ top: 12, right: 10, left: -22, bottom: 0 }}><XAxis dataKey="domain_type" tickFormatter={(value) => titleFor(String(value)).replace(" Receivables", "").replace(" Abandonment", "")} tick={{ fill: "#78879a", fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis allowDecimals={false} tick={{ fill: "#93a0af", fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip cursor={{ fill: "#f4f7fa" }} contentStyle={{ borderRadius: 8, border: "1px solid #e3e9ef", boxShadow: "0 8px 22px #1a273514" }} /><Bar dataKey="case_count" name="Recovery cases" fill="#3974e6" radius={[5, 5, 0, 0]} maxBarSize={42} /></BarChart></ResponsiveContainer></section><section className="panel action-centre"><div className="panel-title"><div><p className="eyebrow">ACTION CENTRE</p><h2>Review queue</h2></div>{reviews ? <button className="link" onClick={onReviews}>Open queue</button> : null}</div>{reviews ? <div className="attention-item"><span className="attention-mark">!</span><div><small>DECISION REQUIRED</small><b>{reviews} recovery case{reviews === 1 ? "" : "s"} awaiting approval</b><p>Review the customer signal before the next contact action.</p></div><button className="attention-button" onClick={onReviews}>Review cases</button></div> : <div className="clear-state"><span>✓</span><b>No decisions waiting</b><small>Cases requiring a specialist will appear here.</small></div>}<div className="queue-summary"><div><span>Active recoveries</span><b>{active}</b></div><div><span>Open payment value</span><b>{money(totalAtRisk)}</b></div></div></section></section>
    <section className="recent-section"><div className="section-heading"><div><p className="eyebrow">ACTIVITY</p><h2>Recent recovery cases</h2></div><button className="link" onClick={() => activity[0] && onCase(activity[0].case_id)}>View case records</button></div><CaseTable cases={cases} onCase={onCase} /></section>
  </div>;
}
